services/web/text2bank_app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField
from wtforms.validators import DataRequired, Email, EqualTo, Length
from text2bank_app import text as txt


class QueryForm(FlaskForm):
    """Form for getting user's query as an input."""

    input = StringField(txt.FORM_DOTAZ,
                        validators=[DataRequired(), 
                        Length(min=3, max=420, message='Dotaz od 3 do 420 písmen')])
    submit = SubmitField(txt.FORM_QUERY_SUBMIT)


class QueryResponseForm(FlaskForm):
    """User response form with three best classified actions as results,
    dropdown menu with all actions and textfield for description"""

    res0 = SubmitField('Výsledek 1')
    res1 = SubmitField('Výsledek 2')
    res2 = SubmitField('Výsledek 3')

    actions = SelectField(txt.FORM_RESP_ELSE, coerce=str, validate_choice=False)
    input_else = StringField(txt.FORM_RESP_NONE_ABOVE)

    res_else = SubmitField(txt.FORM_RESP_SUBMIT_ELSE)


class SignupForm(FlaskForm):
    """User Sign-up Form."""

    name = StringField(
        'Jméno',
        validators=[DataRequired()]
    )
    email = StringField(
        'Email',
        validators=[
            Length(min=6),
            Email(message='Zadej validní email.'),
            DataRequired()
        ]
    )
    password = PasswordField(
        'Heslo',
        validators=[
            DataRequired(),
            Length(min=6, message='Zvol, prosím, dlhší heslo.')
        ]
    )
    confirm = PasswordField(
        'Potvrďte své heslo',
        validators=[
            DataRequired(),
            EqualTo('password', message='Heslá se musí zhodovat.')
        ]
    )
    submit = SubmitField('Registruj')


class LoginForm(FlaskForm):
    """User Log-in Form."""

    email = StringField(
        'Email',
        validators=[
            DataRequired(),
            Email(message='Zadej validní email.')
        ]
    )
    password = PasswordField('Heslo', validators=[DataRequired()])
    submit = SubmitField('Přihlásit se')


class LoginFormAnonym(FlaskForm):
    name = StringField(
        'Jméno / E-mail',
        validators=[DataRequired(), 
        Length(min=3, max=20, message='Prosím zadej jmnéno / email od 3 do 20 písmen')],
        )
    submit = SubmitField('Přihlásit se')

services/web/text2bank_app/__init__.py
from .text2bank import create_app, db

__all__ = ['create_app', 'db']

services/web/text2bank_app/auth.py
from flask import redirect, render_template, flash, Blueprint, request, url_for
from flask_login import current_user, login_user
from sqlalchemy import func

import text2bank_app.text as txt
from .db_helpers import signup_user_anonym
from .forms import LoginForm, SignupForm, LoginFormAnonym
from .models import db, User
from .text2bank import login_manager

auth_bp = Blueprint(
    'auth_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


# @auth_bp.route('/signup', methods=['GET', 'POST'])
# def signup():
#     """
#     User sign-up page.
#     GET requests serve sign-up page.
#     POST requests validate form & user creation.
#     """
#     form = SignupForm()
#     if form.validate_on_submit():
#         existing_user = User.query.filter_by(email=form.email.data).first()
#         if existing_user is None:
#             user = signup_user(form.name.data, form.email.data,
#                                form.password.data)
#             login_user(user)  # Log in as newly created user
#             return redirect(url_for('main_bp.dashboard'))
#         flash(txt.USER_EXISTS)
#     return render_template(
#         'signup.html',
#         title=txt.ACCOUNT_CREATE,
#         form=form,
#         template='signup-page',
#         body=txt.REGISTER
#     )


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main_bp.dashboard'))
    
    form = LoginFormAnonym()
    if form.validate_on_submit():
        user_a = signup_user_anonym(form.name.data)
        login_user(user_a)
        next_page = request.args.get('next')
        return redirect(next_page or url_for('main_bp.dashboard'))
    
    return render_template(
        'login.html',
        form=form,
        title=txt.LOGIN,
        template='login-page',
        body=txt.LOGIN_TEXT
    )



# @auth_bp.route('/login', methods=['GET', 'POST'])
# def login():
#     """
#     Log-in page for registered users.
#     GET requests serve Log-in page.
#     POST requests validate and redirect user to dashboard.
#     """
#     # Bypass if user is logged in
#     if current_user.is_authenticated:
#         return redirect(url_for('main_bp.dashboard'))

#     form = LoginForm()
#     # Validate login attempt
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         if user and user.check_password(password=form.password.data):
#             login_user(user)
#             user.last_login = func.now()
#             db.session.commit()
#             next_page = request.args.get('next')
#             return redirect(next_page or url_for('main_bp.dashboard'))
#         flash(txt.USER_NOT_VALID)
#         return redirect(url_for('auth_bp.login'))
#     return render_template(
#         'login.html',
#         form=form,
#         title=txt.LOGIN,
#         template='login-page',
#         body=txt.LOGIN_TEXT
#     )


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None


@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash(txt.REGISTER_BEFORE_LOGIN)
    return redirect(url_for('auth_bp.login'))

services/web/text2bank_app/controller.py
from flask import session, current_app, make_response, url_for
from flask_login import current_user
from werkzeug.utils import redirect

from text2bank_app import db_helpers as dbh
from text2bank_app.forms import QueryResponseForm

from transformer_eval.celery_workers import get_kb_max_simil, predict


# def evaluate_submitted_query_nb(query_form):
#     session['query_input'] = query_form.input.data
#     query = dbh.add_query(session['query_input'], current_user.id)

#     entities, results, not_sure = evaluating_pipeline(
#         query_input=session['query_input'],
#         evaluator=current_app.config['evaluator'])

#     current_app.logger.debug(f'Extracted entities: {entities}')

#     result_dicts = dbh.write_results(query.id, results)
#     write_to_session(entities, query, result_dicts, not_sure)

#     return make_response(redirect(url_for('main_bp.results')))


# def evaluate_submitted_query(query_form):
#     session['query_input'] = query_form.input.data
#     query = dbh.add_query(session['query_input'], current_user.id)

#     entities, _, _ = evaluating_pipeline(
#         query_input=session['query_input'],
#         evaluator=current_app.config['evaluator'])

#     current_app.logger.debug(f'Extracted entities: {entities}')

#     results, not_sure = transformer_results(
#         query_input=session['query_input'],
#         evaluator=current_app.config['transformer_eval'],
#         validator=current_app.config['clf_ood'])

#     result_dicts = dbh.write_results(query.id, results)

#     current_app.logger.debug(f'Predicted dict results: {result_dicts}')

#     write_to_session(entities, query, result_dicts, not_sure)

#     return make_response(redirect(url_for('main_bp.results')))


# def transformer_results(query_input, evaluator, validator):
#     # predictions = evaluator.predict(query_input, sort_results=True)
#     # not_sure = validator.get_kb_similarity([query_input])[0]['max_simil'] < 0.7
#     return predictions, not_sure


def evaluate_submitted_query(query_form):
    session['query_input'] = query_form.input.data
    query = dbh.add_query(session['query_input'], current_user.id)

    entities, _, _ = evaluating_pipeline(
        query_input=session['query_input'],
        evaluator=current_app.config['evaluator'])

    current_app.logger.debug(f'Extracted entities: {entities}')

    # results, not_sure = transformer_results(
    #     query_input=session['query_input'],
    #     evaluator=current_app.config['transformer_eval'],
    #     validator=current_app.config['clf_ood'])

    result = get_kb_max_simil.apply_async((session['query_input'],), expires=60)
    max_simil = result.get()
    # results = d['predictions']
    # max_simil = d['not_sure']

    evaluator = current_app.config['transformer_eval']
    results = evaluator.predict(session['query_input'], sort_results=True)
    # result = predict.apply_async((session['query_input'],), expires=60)
    # results = result.get()
    
    not_sure = bool(max_simil < 0.7)

    result_dicts = dbh.write_results(query.id, results)

    current_app.logger.debug(f'Predicted dict results: {result_dicts}')

    write_to_session(entities, query, result_dicts, not_sure)

    return make_response(redirect(url_for('main_bp.results')))



def evaluating_pipeline(query_input, evaluator):
    evaluator.fit(query_input)
    current_app.logger.debug(f'Evaluator fitted. Tokens: {evaluator.tokens}')
    results = evaluator.evaluate(sort_output=True)
    entities = evaluator.entities
    current_app.logger.debug(f'Evaluator evaluated probabilities for actions. '
                             f'Tokens: {evaluator.tokens}, '
                             f'Entities: {entities}, Results: {results}')
    probs = [r[0] for r in results]
    not_sure = bool(min(probs) == max(probs))
    return entities, results, not_sure


def write_to_session(entities, query, result_dicts, not_sure):
    session['query_id'] = query.id
    session['query_results'] = result_dicts
    session['entities'] = entities
    session['not_sure'] = not_sure


def validate_and_create_response(query_response):
    current_app.logger.debug('validating on submit')
    if query_response.res0.data:
        dbh.create_response(session['query_id'], result_num=0)
    if query_response.res1.data:
        dbh.create_response(session['query_id'], result_num=1)
    if query_response.res2.data:
        dbh.create_response(session['query_id'], result_num=2)
    if query_response.res_else.data:
        dbh.create_else_response(query_response.actions.data,
                                 session['query_id'],
                                 query_response.input_else.data)


def modified_query_response_form():
    query_resp = QueryResponseForm()

    # action_names = current_app.config['evaluator'].action_names
    action_names = sorted(current_app.config['transformer_eval'].action_names, reverse=False)
    choices = [('', 'Zvol jeden z ostatních záměrů')] + [(g, g)
                                                         for g in action_names]
    query_resp.actions.choices = choices

    query_results = session['query_results']
    action_probas = [qr['action_proba'] for qr in query_results[:3]]
    action_texts = [qr['action_text'] for qr in query_results[:3]]

    query_resp.res0.label.text = f'{action_probas[0]:.2f}%: {action_texts[0]}'
    query_resp.res1.label.text = f'{action_probas[1]:.2f}%: {action_texts[1]}'
    query_resp.res2.label.text = f'{action_probas[2]:.2f}%: {action_texts[2]}'

    return query_resp


def clean_cookies():
    current_app.logger.debug('response commited')
    session.pop('query_id', None)
    session.pop('query_results', None)
    session.pop('entities', None)
    session.pop('not_sure', None)

services/web/text2bank_app/routes.py
from flask import Blueprint, render_template, redirect, \
    url_for, make_response, session, current_app
from flask_login import current_user, login_required

from text2bank_app import db_helpers as dbh
from text2bank_app.controller import evaluate_submitted_query, \
    validate_and_create_response, modified_query_response_form, clean_cookies
from text2bank_app.forms import QueryForm
from text2bank_app import text as txt

main_bp = Blueprint(
    'main_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@main_bp.route('/', methods=['GET', 'POST'])
@login_required
def dashboard():
    """Dashboard with a query form for user input."""
    query_form = QueryForm()

    if query_form.validate_on_submit():
        return evaluate_submitted_query(query_form)

    return render_template(
        'dashboard.html',
        title=txt.TEXT2BANK,
        query_form=query_form,
        template='dashboard-template',
        current_user=current_user,
    )

@main_bp.route('/tip', methods=['GET', 'POST'])
@login_required
def dashboard_tip():
    """Dashboard with a query form for user input."""
    query_form = QueryForm()

    if query_form.validate_on_submit():
        return evaluate_submitted_query(query_form)

    return render_template(
        'dashboard_tip.html',
        title=txt.TEXT2BANK,
        query_form=query_form,
        template='dashboard-template',
        current_user=current_user,
        query_tip=current_app.config['tooltips'].sample(1).iloc[0]
    )


@main_bp.route('/results', methods=['GET', 'POST'])
@login_required
def results():
    """Results page with 3 actions with highest probability,
    textfield and dropdown menu when evaluated badly"""

    query_response = modified_query_response_form()

    if query_response.validate_on_submit():
        validate_and_create_response(query_response)

        clean_cookies()
        return make_response(redirect(url_for('main_bp.thanks')))

    return render_template(
        'results.html',
        title=txt.QUERY_RESULTS,
        query_response=query_response,
        template='dashboard-template',
        current_user=current_user,
        entities=session['entities'],
        query_text=session['query_input'],
        not_sure=session['not_sure'],
    )

@main_bp.route('/thanks', methods=['GET'])
@login_required
def thanks():
    return render_template(
            'thanks.html', 
            current_user=current_user,
            template='help-template'
        )

@main_bp.route("/report")
@login_required
def report():
    """Prints out accuracy report for each class.
    showing top_1 and top_3 accuracy of the model and
    how many times any action was chosen (count).
    """
    responses = dbh.full_queries_responses()
    results = dbh.accuracy_report(responses)
    return results.to_html() 


@main_bp.route("/help")
def help():
    """Shows help"""
    return render_template(
        'help.html',
        title=txt.TEXT2BANK,
        template='help-template',
    )

services/web/text2bank_app/templates/dashboard.html
{% extends "layout.html" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
{% if result_text is defined %}
<h1>{{ result_text }}</h1>
{% endif %}

{% if current_user.is_authenticated %}

<p>Ahoj, {{ current_user.name }}! Jsem <b>Text2Bank</b> - tvůj virtuální bankovní asistent.</p>

<br><br> Co chceš abych za tebe <b>vykonal nebo změnil?</b> <br> 
<b>Nastaly potíže</b> s bankomatem, platbami nebo s platební kartou? <br> 
Zdá se ti, že se někdo <b>naboural</b> do tvého účtu?<br> 
Nebo se chceš prostě na něco <b>zeptat</b>, například ohledně aplikace, změnného kurzu nebo o poplatcích?<br> 


{% if query_form is defined %}

<div class="form-wrapper">

    <div class="logo">
        <img src="{{ url_for('static', filename='img/text2bank.png') }}" alt="logo" />
    </div>

    <form method="POST" action="/">
        {{ query_form.csrf_token }}

        <fieldset>
            <!-- {{ query_form.input.label }} -->
            {{ query_form.input(size=50, placeholder='Zde podrobněji popiš, jaký máš záměr.') }}
        </fieldset>

        <div class="submit-button">
            {{ query_form.submit }}
        </div>

    </form>

    <br>


    <a href="{{ url_for('main_bp.dashboard_tip') }}">Nevíš si rady? Klikni pro tip</a>

</div>

{% endif %}

{% endif %}


<br><br>

{% endblock %}

services/web/text2bank_app/templates/dashboard_tip.html
{% extends "layout.html" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/dashboard.css') }}" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
{% if result_text is defined %}
<h1>{{ result_text }}</h1>
{% endif %}

{% if current_user.is_authenticated %}

<!-- <p>Ahoj, {{ current_user.name }}! Jsem <b>Text2Bank</b> - tvůj virtuální bankovní asistent.</p>

<br><br> Co chceš abych za tebe <b>vykonal nebo změnil?</b> <br> 
<b>Nastaly potíže</b> s bankomatem, platbami nebo s platební kartou? <br> 
Zdá se ti, že se někdo <b>naboural</b> do tvého účtu?<br> 
Nebo se chceš prostě na něco <b>zeptat</b>, například ohledně aplikace, změnného kurzu nebo o poplatcích?<br>  -->


{% if query_form is defined %}

<div class="form-wrapper">

    <div class="logo">
        <img src="{{ url_for('static', filename='img/text2bank.png') }}" alt="logo" />
    </div>

    <form method="POST" action="/">
        {{ query_form.csrf_token }}

        <fieldset>
            <!-- {{ query_form.input.label }} -->
            {{ query_form.input(size=50, placeholder='Zde podrobněji popiš, jaký máš záměr.') }}
        </fieldset>

        <div class="submit-button">
            {{ query_form.submit }}
        </div>

    </form>

    <br>


    <p>Zkus například tohle, jen mi prosím nepiš úplně stejnou větu.</p>

    <p style="font-size: larger;">,,{{ query_tip }}"</p>
    
    <br>
    <a href="{{ url_for('main_bp.dashboard_tip') }}">Stále si nevíš rady? Klikni pro jiný tip</a>

</div>

{% endif %}

{% endif %}


<br><br>

{% endblock %}

services/web/text2bank_app/templates/help.html
{% extends "layout.html" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/help.css') }}" rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}


<div class="help-wrapper">
    <h1>Nápověda</h1>

    <div class="content">
        <p>
            Děkujeme za pomoc na aplikaci <b>Text2bank</b>.
        </p>
        <p>
            Naším cílem je vytvořit jednoduchého textového asistenta pro snadné
            ovládání internetového bankovnictví.
        </p>
        <h2>
            Jak nám pomůžete?
        </h2>
        <p>
            Potřebujeme získat co nejvíce dat „ze života“. Prosíme vás o
            zadávání příkazů a otázek, která se podobají ideálnímu způsobu,
            jakým byste chtěli mluvit s vaším bankovním asistentem.
        </p>
        <p>
            Příkazy by se měly týkat běžných činností (zadat trvalák, zaplatit
            kreditku, zjistit zůstatek na hypotéce…).
        </p>
        <p>
            Čím víc dat takto získáme, tím chytřejší náš systém bude. <b>A právě
                proto potřebujeme Vaši pomoc</b> :)
        </p>
        <br>
        <h2>
            Návod
        </h2>
        <p>
            Na začátku zadejte email a nějaké jednoduché heslo k registraci.
            Poté postupujte takto:
        </p>
        <ol>
            <li>Zadejte svůj příkaz asistentovi (třeba „chci zaplatit
                kreditku“)
            </li>
            <li>Objeví se výsledky, které asistent připraví. <b>Ideální
                    případ:</b></li>
            <ul>
                <li>Téma svého dotazu najdete mezi TOP3 výsledky včetně správně
                    rozpoznaných parametrů dotazu (částka, měna…)
                </li>
                <li>Vyberte správnou možnost a pokračujte zadáním dalšího
                    dotazu
                </li>
            </ul>
            <li>Pokud se asistent <b>netrefil</b> a v TOP3 zadané téma
                nenajdete:
            </li>
            <ul>
                <li>Vyberte jej, prosím, ze seznamu pod nadpisem „Nesedí ani
                    jedno z výše uvedených?“
                </li>
                <li>Případně přidejte svůj komentář či připomínku (např. špatně
                    rozpoznaná částka)
                </li>
                <li>Pak stačí kliknout na tlačítko "Odeslat zpětnou vazbu" a
                    můžete zadat další dotaz.
                </li>
            </ul>

        </ol>
        <br>
        <h2>
            Pár tipů
        </h2>
        <ul>
            <li>Zamyslete se, prosím, co jste za poslední měsíc řešili ve svém
                elektronickém bankovnictví?
            </li>
            <li>Byly to platby, stahování výpisů či jiné činnosti?</li>
            <li>Představte si, že místo klasického ovládání můžete svůj
                požadavek nadiktovat v jedné větě.
            </li>
            <li>Napište cokoliv vás napadne, co byste chtěli od bankovního
                asistenta, aby za vás udělal
            </li>
            <ul>
                <li>Jedná se o triviální každodenní dotazy / něco komplexnější,
                    co třeba řešíte jenom jednou za čas?
                </li>
            </ul>
            <li>Neřešte, jestli je lepší napsat trvalý příkaz nebo opakovaná
                platba, prostě to napište.
            </li>
            <li>Klidně zkuste pro stejnou situaci několik variant, jak vás
                napadá, že by se dal dotaz zadat.
            </li>
            <li>Pomůže i to, když se zeptáte lidí kolem sebe, jak by své dotazy
                napsali oni - čím pestřejší vzorek dotazů, tím lépe.
            </li>
            <li>Nevymýšlejte žádné „špeky“ a finty, zatím se učíme základy.
                Pokud o řešení bude zájem, na špeky určitě ještě dojde v dalších
                kolech 😊
            </li>
        </ul>
        <p>
            <b>Velice děkujeme za celý tým 😊</b>
        </p>
    </div>
    <br>
    <a href="{{ url_for('main_bp.dashboard') }}">Návrat domů</a>
    <br>
    <br>
</div>


{% endblock %}

services/web/text2bank_app/templates/layout.html
<!DOCTYPE html>
<html lang="cz">

<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <title>{{ title }}</title>
    <meta name="description"
          content="Text2Bank aplikace pro Internet Banking."/>
    <meta name="HandheldFriendly" content="True"/>
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
    <meta name="theme-color" content="#5eb9d7"/>
    <link rel="shortcut icon"
          href="{{ url_for('static', filename='img/favicon.png') }}"
          type="image/x-icon"/>
    <link href="https://fonts.googleapis.com/css?family=Helvetica:200,300,500"
          rel="stylesheet"/>
    <link href="{{ url_for('static', filename='css/layout.css') }}"
          rel="stylesheet" type="text/css">
    {% block pagestyles %}

    {% endblock %}
</head>

<body class="{{ template }}">
<div class="container">
      <div class="logo-top">
            <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo" />
        </div>
    {% block content %}{% endblock %}
</div>


<script src="{{ url_for('static', filename='js/main.js') }}"></script>

{% block additionalscripts %}{% endblock %}

<footer>
    <p>
        Kontakt: <a href="mailto:samuel.fabo@profinit.eu" class="">samuel.fabo@profinit.eu</a>,
        <a href="{{ url_for('main_bp.help') }}" class="">Nápověda</a> {{ version_tag }}
    </p>
</footer>


</body>

</html>

services/web/text2bank_app/templates/login.html
{% extends "layout.html" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/account.css') }}"
      rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="form-wrapper">

    <div class="logo">
        <img src="{{ url_for('static', filename='img/text2bank.png') }}" alt="logo"/>
    </div>

    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;
        </button>
        {{ message }}
    </div>
    {% endfor %}

    <h1>{{ title }}</h1>

    <p>{{ body }}</p>

    <form method="POST" action="/login">
        {{ form.csrf_token }}

        <fieldset class="name">
            {{ form.name.label }}
            {{ form.name(size=40, placeholder='tvé jméno, nebo mail@priklad.com') }}
        </fieldset>

        <div class="submit-button">
            {{ form.submit }}
        </div>

    </form>
</div>
{% endblock %}

services/web/text2bank_app/templates/login_.html
{% extends "layout.html" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/account.css') }}"
      rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="form-wrapper">

    <div class="logo">
        <img src="{{ url_for('static', filename='img/logo.png') }}" alt="logo"/>
    </div>

    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;
        </button>
        {{ message }}
    </div>
    {% endfor %}

    <h1>{{ title }}</h1>

    <p>{{ body }}</p>

    <form method="POST" action="/login">
        {{ form.csrf_token }}

        <fieldset class="email">
            {{ form.email.label }}
            {{ form.email(placeholder='vasemail@priklad.com') }}
            {% if form.email.errors %}
            <ul class="errors">
                {% for error in form.email.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </fieldset>

        <fieldset class="password">
            {{ form.password.label }}
            {{ form.password }}
            {% if form.email.errors %}
            <ul class="errors">
                {% for error in form.password.errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </fieldset>

        <div class="submit-button">
            {{ form.submit }}
        </div>

        <div class="login-signup">
            <span>Nemáte účet? <a href="{{ url_for('auth_bp.signup') }}">Registrujte se.</a></span>
        </div>

    </form>
</div>
{% endblock %}

services/web/text2bank_app/templates/results.html
{% extends "layout.html" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/dashboard.css') }}"
      rel="stylesheet" type="text/css">
<link rel="stylesheet" href="https://use.typekit.net/sus7rlu.css">
{% endblock %}

{% block content %}
<h1>{{ body }}</h1>

<!-- {% if current_user.is_authenticated %} -->


{% if query_response is defined %}

<div class="form-wrapper">

    <div class="logo">
        <img src="{{ url_for('static', filename='img/text2bank.png') }}" alt="logo" />
    </div>


    {% if query_text is defined %}

        <!--                    <h3 style="color:#5f6988">Zadaný dotaz:</h3>-->
        <p>Zaznamenal jsem Tvůj záměr:</p>
        <h4 style="color:#5f6988">{{ query_text }}</h4>

        <br>

    {% if not_sure is defined %}
        {% if not_sure %}
            
            <h1, style="color: red;">Mrzí mě to, ale mám pocit, že ti s timhle neumím pomoci.</h1>
            <br>
            <p><i>Jestli nevíš, co všechno umím, vzhlédni na tipy (na hlavní obrazovce). Taky možná stačí, když mi napíšeš tvůj záměr v českém jazyce a užiješ diakritiku.</i><p>
            <br>
            <p, style="font-size: 1.5em;">Myslíš, že jsem se trefil? Klikni na příslušné tlačítko.</p>
            
        {% else %}
            
            <p>Trefil jsem se? Klikni na příslušné tlačítko.</p>

        {% endif %}
    {% endif %}

    {% endif %}



    {% if entities is defined and entities|length > 0 %}
    <h4 style="color:#5f6988">Vyextrahované entity:
        {% for key, value in entities.items() %}
        {{ key }}: {{ value }}
        {% endfor %}
    </h4>
    {% endif %}

    <form method="POST" action="/results">
        {{ query_response.csrf_token }}

        <div class="submit-button">
            {{ query_response.res0 }}
        </div>

        <div class="submit-button">
            {{ query_response.res1 }}
        </div>

        <div class="submit-button">
            {{ query_response.res2 }}
        </div>

        <br>
        <br>

        <p>Netrefil jsem se ani do jednoho z nich?</p>

        {{ query_response.actions }}

        <br>
        <br>

        <fieldset>
            {{ query_response.input_else(size=50, placeholder='a/nebo svůj záměr okomentuj zde.') }}
        </fieldset>


        <div class="submit-button">
            {{ query_response.res_else }}
        </div>


    </form>
</div>


{% endif %}

<!-- {% endif %} -->

{% endblock %}